### ISSUE TITLE
auth.Group.permissions: (fields.E304) Reverse accessor 'Permission.group_set'

### ISSUE THREAD

**Issue by matthewh** [ankitchhatbar/django-group-model#2]
Greetings,

I'm encountering an error using this module to replace `auth.Group` when running makemigrations.. I'm following use case 1 and keeping the same name `group` .

```
❯ ENV=dev.local ./manage.py makemigrations sampleapp
SystemCheckError: System check identified some issues:

ERRORS:
auth.Group.permissions: (fields.E304) Reverse accessor 'Permission.group_set' for 'auth.Group.permissions' clashes with reverse accessor for 'sampleapp.Group.permissions'.
        HINT: Add or change a related_name argument to the definition for 'auth.Group.permissions' or 'sampleapp.Group.permissions'.
sampleapp.Group.permissions: (fields.E304) Reverse accessor 'Permission.group_set' for 'sampleapp.Group.permissions' clashes with reverse accessor for 'auth.Group.permissions'.
        HINT: Add or change a related_name argument to the definition for 'sampleapp.Group.permissions' or 'auth.Group.permissions'.
```

In settings.py

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django_group_model',  # must appear before any app providing user or groups
    'django.contrib.auth',
    ....
]

# https://pypi.org/project/django-group-model/
AUTH_GROUP_MODEL = 'sampleapp.Group'
```

In models.py

```
class Group(AbstractGroup):
    id = KsuidField(primary_key=True, prefix="group_")


class User(AbstractBaseUser, PermissionsMixin):

    id = KsuidField(primary_key=True, prefix="user_")

    groups = models.ManyToManyField(
        'sampleapp.Group',
        verbose_name=_("groups"),
        blank=True,
        help_text=_(
            "The groups this user belongs to. A user will get all permissions "
            "granted to each of their groups."
        ),
        related_name="user_set",
        related_query_name="user",
    )
```

Django 4.2, Python 3.10

What am I doing wrong?
